[/]
custom-list=['custom0', 'custom1', 'custom2', 'custom3']

[custom-keybindings/custom0]
binding=['Pause']
command='gpaste-client ui'
name='gpaste ui'

[custom-keybindings/custom1]
binding=['F9']
command='wmctrl -xa thorium'
name='focus thorium'

[custom-keybindings/custom2]
binding=['F10']
command='wmctrl -xa terminal'
name='focus terminal'

[custom-keybindings/custom3]
binding=['F8']
command='wmctrl -xa zed'
name='focus zed'

[wm]
close=['F6']
switch-windows=['F4']
toggle-fullscreen=['F11']
toggle-maximized=['F1']
